# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Setup
url:                 http://yongchol.github.io

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             ''

title:               Roy's dev note

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  dreaming the day better than yesterday.
# The tags listed as entries in the sidebar
sidebar_tags:        [spring, nodejs, python, think]

# Fallback image and color if not overwritten for tag or post
image:               /public/img/home.jpg
color:               '#A85641'

# Fonts
font:                '"PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:              'Roy'

  # This photo will be used in the about section
  photo:             /public/img/profile.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:             |
    updated soon .
    
  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    #facebook:        yongchol.shin.7
    # twitter:         _username_
    # google:          _number_
    # instagram:       _username_
    github:          yongchol
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # linkedin:        _firstname_-_lastname_-_string_

# Remove to disable Google Anaylics
#google_analytics_id: 'UA-84025722-2'

# Setting a disqus subdomain will enable the comment section
  disqus:            yongcholgithubio

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
