# Add an entry, where the key represents a slug.
# Provide at least a `name` value and optionally `image`, `color` and `description`.
# Markdown is enabled for `description`, however don't use more than one paragraph (enforced by `>`)
#
# Example:
#
# ~~~
# mytag:
#   name: My Tag
#   description: >
#     *My Tag* is an example of how to define a custom tag.
# ~~~

think:
  name: think
  image: /public/img/home.jpg

nodejs:
  name: nodejs
  image: /public/img/home.jpg

spring:
  name: spring
  image: /public/img/home.jpg

python:
  name: python
  image: /public/img/home.jpg
